resources:
- ../../base

namespace: fintech-prod

patches:
- target:
    kind: Deployment
    name: txn-service
  patch: |
    - op: replace
      path: /spec/replicas
      value: 5
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: "1Gi"