replicas: 1

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 1
    memory: 2Gi

esConfig:
  elasticsearch.yml: |
    xpack.security.enabled: false
    discovery.type: single-node

volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi