architecture: replicaset
replicaCount: 3

auth:
  enabled: false

persistence:
  enabled: true
  size: 5Gi

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi