apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: txn-hpa
  labels:
    app: txn-service
    tier: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: txn-service

  minReplicas: 2
  maxReplicas: 5

  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30

    scaleDown:
      stabilizationWindowSeconds: 120
      policies:
      - type: Percent
        value: 25
        periodSeconds: 60

  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60

  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70